# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '__first__'),
        ('adminacc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('eventid', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('details', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='events/')),
                ('youtubelink', models.URLField()),
                ('eventformat', models.CharField(max_length=1000)),
                ('websitelink', models.URLField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('contacts', models.ManyToManyField(to='adminacc.AdminUser')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Events')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.RegUser')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('rule', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='rules',
            field=models.ManyToManyField(to='events.Rule'),
        ),
    ]
