# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_inapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
    ]
