# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=gallery.models.getDirectory)),
                ('likes', models.IntegerField()),
                ('description', models.CharField(max_length=2000)),
                ('approved', models.BooleanField(default=False)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.RegUser')),
            ],
        ),
        migrations.AddField(
            model_name='likehistory',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Upload'),
        ),
        migrations.AddField(
            model_name='likehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.RegUser'),
        ),
    ]
