# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
