# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
