# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0002_auto_20160724_2125'),
        ('events', '0002_auto_20160809_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.RegUser')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
